### ISSUE TITLE
Backend::add_directive

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#145]
Currently there is no backend support for adding show or heuristic directives.

**Comment by rkaminsk** [comment]
I can add the remaining directives for the next release. They are already available via the C API.

Just as a note. Anything you can do with the backend, can also be done using grounding. If you find yourself adding complicated programs via the backend, you should consider to encode your problem in a non-ground program augmented with external functions.

**Comment by rkaminsk** [comment]
Closed with 5c49b4854f732ad2580b3bae1b9cf412b221b542. Note that I did not add show directives because these are not available in the C-API, either. Supporting show directives is possible in principle. There is just the question how to implement them. For example, gringo does quite some processing to not print terms twice...
