### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by 0x326** [potassco/clingo#148]
I know clingo is published as an Anaconda module but I think it would also be convenient if it were published to PyPI as well, for non-anaconda users.

I'm not too familiar with Python packaging myself, but I believe it would be possible to publish the compiled `clingo` module as a binary "wheel".

These links might be helpful, but I haven't found one yet that explicitly mentions the steps required to C-based projects:

- https://docs.python-guide.org/shipping/packaging/
- https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives
- https://python-packaging.readthedocs.io/en/latest/index.html
- https://realpython.com/pypi-publish-python-package/

**Comment by rkaminsk** [comment]
I have been looking at python's distutils in the past and did not manage to put together something that works cross-platform. That's why I decided to go with anaconda in the end. I do not want to spend any more time here. But I might be able to provide some help with clingo related issues if someone else wants to try.
