### ISSUE TITLE
How to set time limit in C clingo-API

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#154]
I am using **C clingo-API**. Similar to #151, I was trying to set some time-limit for each **clingo solve**. I have tried with **clingo_solve_mode_async** and  **clingo_solve_handle_wait()**. Finally, I write the following function:
```
bool solve(clingo_control_t *ctl, model_buffer_t *data, clingo_solve_result_bitset_t *result)
{
    bool ret = true;
    bool timeout = false;  // parameter of clingo_solve_handle_wait()
    double remaining_time = TIMEOUT;   // TIMEOUT is the time-limit I want to set
    clingo_solve_handle_t *handle;
    clingo_model_t const *model;
    clock_t tStart = clock();
    // get a solve handle
    if (!clingo_control_solve(ctl, clingo_solve_mode_async|clingo_solve_mode_yield, NULL, 0, NULL, NULL, &handle))
    {
        goto error;
    }
    // loop over all models
    while (true)
    {
        if (!clingo_solve_handle_resume(handle))
        {
            goto error;
        }
        // wait for the remaining time 
        clingo_solve_handle_wait(handle, remaining_time, &timeout);
        if (!clingo_solve_handle_model(handle, &model))
        {
            goto error;
        }
        // check whether we get all models
        if (!model)
        {
             break;
        }
        // calculate residual time
        remaining_time -= (double)(clock() - tStart)/CLOCKS_PER_SEC;
        if ( remaining_time <= 0.0 ) {
            // solving timeouted
            break;
        }
        tStart = clock(); 
    }
    // close the solve handle
    if (!clingo_solve_handle_get(handle, result))
    {
        goto error;
    }
    goto out;

error:
    ret = false;

out:
    return clingo_solve_handle_close(handle) && ret;
}
``` 
Really, I am not sure whether it will work on all cases. 
What is the better way to set time-limit on **clingo solve**?

**Comment by rkaminsk** [comment]
You have to check the `result` flag of the [wait] function. Something like:
```cpp
remaining_time = TIMEOUT - (double)(clock() - tStart)/CLOCKS_PER_SEC;
finished = false;
if (remaining_time > 0) {
    clingo_solve_handle_wait(handle, remaining_time, &finished);
}
if (!finished) {
    clingo_solve_handle_cancel(handle);
    break;
}
```
Also you should calculate the remaining time directly before calling wait. If that time is less than zero, you should call cancel instead of wait.

This is the clean way to implement this with clingo's C-API. You could also call [interrupt] from another thread (or I believe a signal handler would work) but then you have to deal with signals and threads, which comes with its own share of problems.

[wait]: https://potassco.org/clingo/c-api/current/group__solvehandle#ga96d87fd2361f2d92f995cf1d2fc0001c
[interrupt]: https://potassco.org/clingo/c-api/current/group__control#ga68d85962372b1258bc6726753cdecaa8
