### ISSUE TITLE
Static building & linking of clingo library

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#156]
I am using **C clingo-API**. For some reason, I want to **build** clingo library **statically** and create a binary executable (static) that **links** clingo library **statically**.
I built clingo library statically by using flag `-DCLINGO_BUILD_STATIC=ON` during execution of `cmake` command.  Then, `libclingo.a` library file is created.
To create static binary, I executed the following command:
```
g++ test.c -static -I./libclingo -L./Build/lib -lclingo
```
Here, test.c is a C program that includes `clingo.h` header file,  `./libclingo` and  `./Build/lib` are two directories that contain **clingo.h** header file and **libclingo.a** static library respectively.
Unfortunately, after execution I got a bunch of `undefined reference` error. I have included here a small portion of error. 
```
incmode.cc:(.text+0xaf3): undefined reference to `Gringo::Symbol::name() const'
incmode.cc:(.text+0xb02): undefined reference to `Gringo::Symbol::num() const'
/home/mahi/Study/Tools/clingo/Build/lib/libclingo.a(incmode.cc.o): In function `Gringo::incmode(clingo_control&)':
incmode.cc:(.text+0xcbb): undefined reference to `Gringo::String::String(char const*)'
collect2: error: ld returned 1 exit status
```
I have spent few hours to understand the error. Sorry for lengthy description.

**Comment by rkaminsk** [comment]
When building statically, you have to make sure that all the other static libraries the clingo project is composed of are also included. Have a look at the build log when the clingo executable is linked. And be careful. The order in which static libraries are passed to the linker matters. Also, since clingo uses threads, static linking is not officially supported with gcc. Have a look at the [release.sh](/potassco/clingo/blob/master/scratch/release.sh) script, which has workarounds for these problems.

With all of this said, I am not going to officially support static linking. It's just too messy...

**Comment by sthiele** [comment]
Hi, i build a static library for the rust-wrapper. it does not use cmake though also it does not have all features like python support. Also i am not sure if multi threading works. But it might help you anyway.
https://github.com/potassco/clingo-rs/blob/master/clingo-sys/build.rs

**Comment by mahi045** [comment]
@sthiele thanks.
Unfortunately, I have no knowledge on rust-wrapper. By seeing the file build.rs, I am guessing that the order of linking libraries is: `-lpotassco  -lclasp  -lgringo -lclingo -lreify`.
