### ISSUE TITLE
Backend ctors

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#165]
I try to use the C++ Clingo::Backend class, but I have trouble to control the preparing and finalizing of the backend.
I think it would cause trouble to copy an object of the backend, like
`Backend x = c.backend();`
since if one object is destroyed no other Backend will be valid.

Would it make sense to delete the cctor and maybe implement a move ctor ?

**Comment by rkaminsk** [comment]
I can add a move constructor.

**Comment by MaxOstrowski** [comment]
Awesome, thanks.

**Comment by rkaminsk** [comment]
> `Backend x = c.backend();`

No copy is happening here. But it is the right thing to delete the copy constructor. I decided to change this to a bug because the interface is misleading and easily used wrongly. And with C++11 the code depends on the copy elision optimization (with C++17 the code works fine but the copy constructor still should be deleted).
