### ISSUE TITLE
How to parse clingo symbol to string in c++?

### ISSUE THREAD

**Issue by chandanavgermany** [potassco/clingo#206]
for (auto &atom : m.symbols()) {
		                std::cout << " " << (string)atom << " " << typeid(atom).name();
		            }

I want to parse atom as a string, but I am getting error.

**Comment by rkaminsk** [comment]
There is a `<<` operator for symbols. Just remove the cast.

**Comment by chandanavgermany** [comment]
No, Actually I want to parse the content of atom symbol.

**Comment by rkaminsk** [comment]
I don't know what you mean.

**Comment by chandanavgermany** [comment]
I will give an example.

Assume i get atom = "change_lane(2,3)". I want to extract character 2,3 from the atom symbol. So I thought first I need convert the atom to string type, then extract the numbers from the string.

**Comment by rkaminsk** [comment]
I would not recommend  to do any parsing because the `Symbol` class provides all the methods you need. You could however use a [std::ostringstream] to convert a symbol to a string.

Just have a look at the public interface of the `Symbol` class instead:

```cpp
class Symbol {
public:
      int number() const;
      char const *name() const;
      char const *string() const;
      bool is_positive() const;
      bool is_negative() const;
      SymbolSpan arguments() const;
      SymbolType type() const;
      std::string to_string() const;
      bool match(char const *name, unsigned arity) const;
      size_t hash() const;
};
```

Do get the values in your examples you could use:

```cpp
if (atom.match("change_lane", 2) {
  auto args = atom.arguments();
  auto a = args[0].number();
  auto b = args[1].number();
}
```

Always have a look at the class declarations in the [clingo.hh] file. Unfortunately, only [clingo's C API][c-api] is documented. I do not have the time and energy to document the C++ API, too. But the C++ API is mostly a straightforward wrapper around the C API. I recommend you use a modern C++ IDE together with the C API documentation. This will make writing code so much less painful.

PS: I do not know if the last release already has a `Symbol::match` function. If not, you would have to implement it using `Symbol::type` and `Symbol::arguments` yourself. Also, real code should check the type of the arguments before calling `Symbol::number`.

[c-api]: https://potassco.org/clingo/c-api/current/
[std::ostringstream]: https://en.cppreference.com/w/cpp/io/basic_ostringstream
[clingo.hh]: https://github.com/potassco/clingo/blob/master/libclingo/clingo.hh

**Comment by chandanavgermany** [comment]
Thanks it worked.
