### ISSUE TITLE
port to iOS

### ISSUE THREAD

**Issue by jeffxtang** [potassco/clingo#223]
Anyone has any ideas/suggestions on how to port Clingo to iOS so one can run it directly in an iOS app?

**Comment by rkaminsk** [comment]
I have never developed apps for mobile devices. Maybe the current code base can already be compiled for iOS or Android or maybe adjustments are needed. On another note, it is possible to compile clingo to JavaScript with Emscripten. This won't offer the same performance as a C++ library but might be easier to integrate in an app/website. Also, since clingo is very resource hungry, I am not sure a mobile phone is the right target device (but then even complex games are possible there today).

**Comment by jeffxtang** [comment]
Thanks @rkaminsk. I'll give it a try soon to see if I can build the current code base on iOS or what it takes to do so..

**Comment by rkaminsk** [comment]
If you need any patches please feel free to open a PR. I have access to Xcode or VS, which I think both provide tools to develop iOS apps. In case there are problems, I might be able to have a look. No promises though.
