### ISSUE TITLE
Variables created during propagator initialization are not frozen and might be eliminated by preprocessing.

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#226]
[bug.zip](https://github.com/potassco/clingcon/files/4880155/bug.zip)

While calling
`clingcon encoding.lp types.lp test.lp --stats 0`
gives the expected results
adding any `--conf=XXX` like jumpy results in a segfault.

**Comment by rkaminsk** [comment]
> I was thinking to provide a way to disable program updates because a lot of users were asking for a mode where the library would behave exactly as clasp's single shot solving.

I cannot provide an option to disable program updates because the clingo API needs access to program literals from the logic program in the model callback (and there is no (reasonable) way around this). I will simply provide `PropagateInit::freeze` and `PropagateInit::unfreeze` methods and add a default enabled freeze flag to the `PropagateInit::add_literal` method. The (expert) user knows best what to freeze/unfreeze anyway.

**Comment by rkaminsk** [comment]
@BenKaufmann I had a look at clasp's facade.  Currently `ClaspFacade::prepare` releases the the logic program whenever program updates have not been enabled. I think that all I need to enable single shot solving with the API is to prevent the facade from deleting the logic program. Would it be (easy enough) possible to add an option for this too? Maybe just a function to initialize `ClaspFacade::accu_`?

**Comment by BenKaufmann** [comment]
>  I think that all I need to enable single shot solving with the API is to prevent the facade from deleting the logic program. 
> Would it be (easily) possible to add an option for this? Maybe just a function to initialize ClaspFacade::accu_? 

Initializing `ClaspFacade::accu_` wouldn't help. It is only needed/useful in the context of multi-step solving.  Instead, we would have to change `LogicProgram::dispose()` so that it does not automatically remove the whole program if program updates are not enabled, ClaspFacade should then distinguish three modes: a) single-shot, no-script, b) singleshot, with script, c) multishot and call   
`LogicProgram::dispose(true)` only if mode a) is active.

> Would it still be possible to get the truth value of (selected) atoms in the logic program in the model callback even if their 
> associated variables were eliminated? Or does clasp freeze all "output" atoms anyway?

Clasp does not freeze "output" atoms and eliminated variables are not part of a solver assignment. However, models are always extended to all variables and hence also contain an assignment for eliminated variables.

**Comment by rkaminsk** [comment]
> Initializing `ClaspFacade::accu_` wouldn't help. It is only needed/useful in the context of multi-step solving. Instead, we would have to change `LogicProgram::dispose()` so that it does not automatically remove the whole program if program updates are not enabled, ClaspFacade should then distinguish three modes: a) single-shot, no-script, b) singleshot, with script, c) multishot and call `LogicProgram::dispose(true)` only if mode a) is active.

I thought that initializing `acc_` would give us something like mode b) because the program won't be disposed. We might even need it to keep the `on_statistics` callback I implemented special-case free.

> Clasp does not freeze "output" atoms and eliminated variables are not part of a solver assignment. However, models are always extended to all variables and hence also contain an assignment for eliminated variables.

This would mean that in mode b) I would also have to adjust the cleanup function because I can no longer assume that a program literal is associated with a valid solver literal. It looks like this feature would require quite a lot of testing on my side. Maybe better skip it.

```cpp
void ClingoControl::cleanup() {
    if (!clingoMode_ || !canClean_) {
        return;
    }
    canClean_ = false;
    Clasp::Asp::LogicProgram &prg = static_cast<Clasp::Asp::LogicProgram&>(*clasp_->program());
    Clasp::Solver &solver = *clasp_->ctx.master();
    auto assignment = [&prg, &solver](unsigned uid) {
        Potassco::Value_t truth{Potassco::Value_t::Free};
        bool external{false};
        if (prg.validAtom(uid)) {
            external = prg.isExternal(uid);
            Clasp::Literal lit = prg.getLiteral(uid);
            if (solver.isTrue(lit)) { truth = Potassco::Value_t::True; }
            else if (solver.isFalse(lit)) { truth = Potassco::Value_t::False; }
        }
        return std::make_pair(external, truth);
    };
    auto stats = out_->simplify(assignment);
    LOG << stats.first << " atom" << (stats.first == 1 ? "" : "s") << " became facts" << std::endl;
    LOG << stats.second << " atom" << (stats.second == 1 ? "" : "s") << " deleted" << std::endl;
}
```

**Comment by rkaminsk** [comment]
I am keeping it simple. Clothing this.
