### ISSUE TITLE
What is the difference between clingo and clasp projects

### ISSUE THREAD

**Issue by yurivict** [potassco/clingo#297]
```clasp``` only installs ```bin/clasp```, and ```clingo``` installs more files including ```bin/clasp```.

We have both ```clasp``` and ```clingo``` as separate ports on FreeBSD.

Is ```clasp``` entirely included in ```clingo``` and it doesn't make sense to install it separately?

**Comment by rkaminsk** [comment]
clasp and clingo are bundled together. Since many years, clingo releases immediately follow clasp releases. In principle, it is not necessary to have two different packages. It is possible to disable installation of clasp's binaries via an option when installing clingo. I can imagine that this leads to a smaller installation if someone only needs clasp. But we are talking about one or two megabytes here.

**Comment by yurivict** [comment]
Ok, thanks.
