### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by rilopez3** [potassco/clingo#319]
What metrics do you recommend to evaluate the performance of the solver? 
In my research team, we are trying to compare the performance of a model in clingo asp vs max-sat

**Comment by rkaminsk** [comment]
Maybe do it the same way as in the [MaxSAT evaluations](<https://maxsat-evaluations.github.io/>)?

**Comment by rilopez3** [comment]
Thanks for the quick reply, I'll take a look at it.
Using the classic metrics (num vars, num clauses, num decisions, num conflicts) we have not reached conclusive results, so we are evaluating other options.

**Comment by rkaminsk** [comment]
> Thanks for the quick reply, I'll take a look at it.
> Using the classic metrics (num vars, num clauses, num decisions, num conflicts) we have not reached conclusive results, so we are evaluating other options.

Problem statistics can of course be correlated to solver performance but I do not see what this has to do with the performance evaluation of solvers?

**Comment by rilopez3** [comment]
My question is precisely about the quality of the solution, I have surely explained myself wrong.

We have 2 encodes for a problem that we have evaluated in ASP clingo and Max-Sat, encode 1 has a better performance in Clingo and encode 2 in Max-Sat (encodes differ in a couple of restrictions). So we are trying to understand why? We think they may differ in the way they propagate or in the way constraints are represented internally in each solver.

Using the classic metrics (num vars, num clauses, num decisions, num conflicts) we have not reached conclusive results.
For this reason, we would like to know if there is any extra metric, from those available in the statistics of the solution, that we can obtain, or how we could evaluate it with the available statistics.

Thanks again for the help

**Comment by rkaminsk** [comment]
I see. I think it is difficult to compare just using the statistics. There are things like model level, backjumps, number of choices, which might give some idea about the propagation. Otherwise, it might be a good idea to look at the encoding and think about which one allows for stronger propagation.

**Comment by MaxOstrowski** [comment]
It may also help to translate the Maxsat encoding to ASP to spot differences and similarities. And also use clingo to solve the other encoding to rule out differences in the solver.

**Comment by rilopez3** [comment]
We just did this, but the statistics of the solution do not show significant variations. That is why we believe that the difference may be in the propagation or the internal representation.
We were hoping that there would be a method that would allow further debugging of the resolution.

As extra information, we are modeling a variant of the MAPF problem (Multi-Agent Path Finding), with which we achieve a breakthrough in the state of the art (conference paper in proceedings).
Now, we are looking at the difference in performance, and we find that the classic metrics are not significantly different from previous models.

**Comment by daveraja** [comment]
@rilopez3 I don't pretend to understand this conversation as it is not clear to me how the solver's general metrics can tell you useful information about the solution quality; since it seems like solution quality is inherently domain specific. But I'd be interested if you have a pointer to your conference paper (or a prerelease/arXiv version). Cheers.

**Comment by rkaminsk** [comment]
> We just did this, but the statistics of the solution do not show significant variations. That is why we believe that the difference may be in the propagation or the internal representation.

This is too vague to say anything more. We do not even know what you are actually comparing. For example, we do not know if you can solve the problems optimally or you just get sub-optimal solutions.

**Comment by robertoasin** [comment]
Hi, I'm a co-author of the work. We have two ASP encodings for the MAPF problem. Both solve the problem optimally, but the latest one clearly outperforms the first one and we would like to go into deep into why the latest encoding works so well. In SAT, we would analyze things like the number of decisions per variable, the number of propagations per decision, number of propagations per second or explore further metrics of the search, in order to identify if the reason for our results is related to the quality of the search. Of course, we would also like to compare the size of the encodings. Is there any specification of the meaning of the stats the solver can provide?

**Comment by rkaminsk** [comment]
> Hi, I'm a co-author of the work. We have two ASP encodings for the MAPF problem. Both solve the problem optimally, but the latest one clearly outperforms the first one and we would like to go into deep into why the latest encoding works so well. In SAT, we would analyze things like the number of decisions per variable, the number of propagations per decision, number of propagations per second or explore further metrics of the search, in order to identify if the reason for our results is related to the quality of the search.

Interesting because this is not how we usually do it. Instead we typically start from a basic encoding and then optimize it step by step benchmarking the effects.

I think we do not have the statistics you are asking for available. I am not sure if this helps but we also have Minisat-like progress information, which can be enabled with option `-V3`. @BenKaufmann might be able to tell you more.

> Of course, we would also like to compare the size of the encodings.

For this, the Variables and Constraints in the statistics output are probably a good idea.

> Is there any specification of the meaning of the stats the solver can provide?

I am not aware that we ever published a detailed description.

**Comment by BenKaufmann** [comment]
> @BenKaufmann might be able to tell you more.

I can't unfortunately. What is printed via `--stats -V3` (or `stats=2 -V3` if multi-threading is enabled) is all there is. An outdated (but still somewhat helpful) descirption of the statistics can be found in the [mailing list archive](https://sourceforge.net/p/potassco/mailman/message/30518330/). As one can see, there is nothing like "number of decisions per variable" or "number of propagations per decision/second" but one could try to approximate some information via `Choices` to `Conflicts` ratio and the solving time. 

Anyhow, I would probably play around with clingo/clasp's basic search/optimization configurations and then have a look at search statistics, in particular, `Choices`, `Conflicts`, `Restarts`, and number/size of learnt `Lemmas`.

**Comment by robertoasin** [comment]
Thank you very much.

Just one last question. Can we make the equivalence of clingo Choices to,
what we call, in SAT-solvers, Decisions?

**Comment by rkaminsk** [comment]
>  Just one last question. Can we make the equivalence of clingo Choices to, what we call, in SAT-solvers, Decisions?

Yes, it's the same.
