### ISSUE TITLE
Allow Control.load to manage parameters like Control.add

### ISSUE THREAD

**Issue by jachymb** [potassco/clingo#321]
If I want to emulate the functionality of the `-c` switch of gringo/clingo via the Python API, it cannot be directly done with the `Control.load` function. I made a workaround like this:

```python
 class MyControl(Control):
     def load_add(self, name, parameters, file):
         with open(file) as f:
             program = f.read()
         self.add(name, parameters, program)
```

But that feels a bit clunky. I believe the `Control.load` function itself should be able to achieve a similar effect itself. Maybe there is a better way that I don't know of?

**Comment by rkaminsk** [comment]
This does not really emulate the `-c` switch because its effect is global affecting the whole program. You could add a program with a `#const` directive and then load a file. This would have the "same" effect as the `-c` switch. As long as the programs you are adding are small enough, there is also no problem with your code. Just large instances are better loaded using `Control.load`.

**Comment by jachymb** [comment]
Ok, but is there a convenient way to set the `#const` directive programatically? I mean, there is the `Control.get_const`  method, but apparently no `set_const` method. I could work around that by reading the file to string and appending a `#const` directive, but again, that feels pretty clunky.

**Comment by rkaminsk** [comment]
There is no function to set it conveniently but there are different ways to set it. The most "convenient" way is probably by passing `['-c', 'name=<value>']` as arguments to the control object. Otherwise, `#const` statements can also be added via the ast module. This avoids strings but is quite verbose. You could also avoid `#const` statements completely and just pass the value via a fact.

**Comment by jachymb** [comment]
>  The most "convenient" way is probably by passing `['-c', 'name=<value>']` as arguments to the control object. 

OK, that seems like a relatively clean solution to my problem. Didn't know that's possible. Thanks for your time!
