### ISSUE TITLE
Control.py broken? 

### ISSUE THREAD

**Issue by ZimneJonas** [potassco/clingo#323]
I seem to have problems with **control.py**.
  I expect to have done some mistake while installing. 
  
  1. This is an Error i get for running something like 'ctl.ground([("step",[42])])' in the python API:
  
  File "/home/zimne/anaconda3/envs/tel/lib/python3.9/site-packages/clingo/**control.py**", line 335, in ground
    c_part.params[i] = sym._rep
AttributeError: 'int' object has no attribute '_rep'

2. And this is an error if I am running the Asprilo Visualizer:

  File "/home/zimne/anaconda3/envs/tel/lib/python3.9/site-packages/visualizer-0.2.2-py3.7.egg/visualizer/parser.py", line 206, in parse
AttributeError: '**Control**' object has no attribute 'builder'

**Comment by ZimneJonas** [comment]
*The same programs do run on 5.4 though

**Comment by MaxOstrowski** [comment]
I think the API interface has slightly changed in the latest update. Wrap the 42 inside Clingo.Number().-------- Originalnachricht --------Betreff: Re: [potassco/clingo] Control.py broken?  (#323)Von: ZimneJonas An: potassco/clingo Cc: Subscribed 
*The same programs do run on 5.4 though

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/potassco/clingo/issues/323#issuecomment-881929492",
"url": "https://github.com/potassco/clingo/issues/323#issuecomment-881929492",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tortinator** [comment]
Hi @ZimneJonas ! Thanks for pointing this out to us! In fact, the paper at archive will ultimately align with 5.5 (have you checked the recent version ?), once it is published. We just pre-published its preliminary version that only ran with an intermediate version. Sorry for any inconvenience!

**Comment by rkaminsk** [comment]
I am going to open an issue for the asprilo visualizer.

**Comment by NikoRW** [comment]
Hi, I tried to run the examples published in 'Multi-shot ASP solving with clingo' section 5.1, Listing 5, 6 and 7 [https://arxiv.org/abs/1705.09811](url) and encountered the same error as Jonas. I followed the advice to wrap the parameters inside the number method and now I'm getting :
File "/home/niko/anaconda3/lib/python3.9/site-packages/clingo/symbol.py", line 248, in Number
    _lib.clingo_symbol_create_number(number, p_rep)
TypeError: an integer is required
Did I make a mistake or is there also an updated version for this paper?

**Comment by rkaminsk** [comment]
Please do not comment on long closed issues and rather use a new one. Please open a new one and also show us the code you are trying to run.
