### ISSUE TITLE
Python RuntimeError when using --models > 0

### ISSUE THREAD

**Issue by drwadu** [potassco/clingo#365]
I'm trying to enumerate `n` models as described in the following minimal example snippet:
```python
n = 0
ctl = Control(str(n))

# grounding, collecting assumptions etc.

with ctl.solve(assumptions=assumptions, yield_=True) as handle:
    models = [f"{model}".split(" ") for model in handle]
```
However, whenever I choose `n` > 0, I run into:  **RuntimeError: In context '<libclingo>': multiple occurrences: 'models**'

How can I potentially resolve the problem?

**Comment by rkaminsk** [comment]
The [initializer of the Control class](https://potassco.org/clingo/python-api/5.5/clingo/control.html#clingo.control.Control) expects a sequence of strings. Since Python has no character type, a string is also sequence of strings. Even a type checker will not find this bug. You should pass `[str(n)]` instead. Alternatively, you can also use the [Configuration class](https://potassco.org/clingo/python-api/5.5/clingo/configuration.html) to set the number of models to enumerate: `ctl.configuration.solve.models = n`.

**Comment by drwadu** [comment]
Okay, just to check, whether I understand: The solver has gotten multiple `--models` configurations, e.g. `n = 10`, means `--models=1` and `--models=0`, so, I can avoid `List` whenever `n` consists of no more than one digit, right?
