### ISSUE TITLE
cmake shows no warning and pyclingo module is built but does not work if python3-dev is missing

### ISSUE THREAD

**Issue by peschue** [potassco/clingo#44]
I have observed this with python3 on Ubuntu 16.04, but maybe it is also true with python2 and on later versions.

If I do not have python3-dev installed (maybe the real requirement is libpython3-dev) then cmake configures nicely for python3 and the build also succeeds and make install yields a nice clingo*.so file that has no PyInit_clingo therefore any import will fail.

Installing python3-dev and rebuilding fixes the problem.

**Comment by rkaminsk** [comment]
I am not sure what you mean. If no python development headers are present on the system, then no clingo python module is build. Did you check? Maybe a module for python 2 has been build instead of one for python 3. In python 2 the init function has a different name.

What might happen is that a python 3 interpreter is found and a python 2 library build. The problem here is that, unfortunately, there are two different cmake modules for detecting python: [FindPythonInterp](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html) and [FindPythonLibs](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html). I could compare the versions found but am not sure how robust this would be. The cmake documentation is rather sparse at this point.

**Comment by peschue** [comment]
The Python2 modules always had the name clingo.so while the module that was built in my case had the name clingo.cpython-35m-x86_64-linux-gnu.so although of course there could be a Python2 module inside. 

I will check if the python2 library is built for the python3 interpreter and come back with more information.

**Comment by peschue** [comment]
It is as you expected.

I specify python3 as interpreter and I saw that this selects the correct python library (usually) which has a much more complicated and less straightforward name than /usr/bin/python3.

If python3 is there but libpython3-dev is not, this detects python2.7 dev libraries.

As a result a python2.7 plugin is built that has the name of a python3.4 plugin (the version obtained from FindPythonInterp).

I have attached two logs of both situations done on Ubuntu 16.04.

[clingo-build-pyclingo-with-libpython3-dev.txt](https://github.com/potassco/clingo/files/1057637/clingo-build-pyclingo-with-libpython3-dev.txt)
[clingo-build-pyclingo-without-libpython3-dev.txt](https://github.com/potassco/clingo/files/1057639/clingo-build-pyclingo-without-libpython3-dev.txt)

It is interesting that FindPythonInterp and FindPythonLibs interacts in a way that the former determines the preference of the latter for selecting the development libraries.

Is there a generic way to say "i want python3 development libraries, whatever version there is on the system" without using the trick via the interpreter?

**Comment by rkaminsk** [comment]
The [documentation of the FindPythonLibs module](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html) says that the following variables should be set:
- `PYTHON_LIBRARY` - path to the python library
- `PYTHON_INCLUDE_DIR` - path to where Python.h is found

The safest way is probably to do it as the cmake modules for finding python suggest: install the requried development headers and set the `PYTHON_EXECUTABLE` variable to the corresponding interpreter.

I would have preferred if there was an easy way to make sure everything fits together. With the cmake modules, I do not see an easy way though.

**Comment by peschue** [comment]
Thank you for this pointer. I guess it is good enough that `cmake` displays the python library version. So the problem can be diagnosed with this.

The only thing that could be fixed: the module is named according to `FindPythonInterp` but compiled according to `FindPythonLibs` which leads to the inconsistency of a Python2 module inside a Python3 module library file. If the module could obtain its name according to `FindPythonLibs` then python3 would not even attempt to load it and python2 could load it.

**Comment by rkaminsk** [comment]
> If the module could obtain its name according to FindPythonLibs then python3 would not even attempt to load it and python2 could load it.

The problem is that to get the naming convention, one needs the python interpreter. See the `cmake/python-site.py` script. One could of course write some C code to execute the script just using the libraries but this would be quite involved.

I think I am just going to put a note in the installation instructions that the user has to take care here.

**Comment by peschue** [comment]
Thank you. :+1:
