### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'ASTSequence' and 'ASTSequence'

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#450]
`TypeError: unsupported operand type(s) for +: 'ASTSequence' and 'ASTSequence'`

According to 
https://www.oreilly.com/library/view/python-in-a/0596001886/ch04s06.html
sequences should have a + operator ? I have no clue though ...

**Comment by rkaminsk** [comment]
The ASTSequence implements `collections.abc.MutableSequence`. So it should provide a `+=` operator but does not have to provide a `+` operator. It is also not really possible to provide one because `ASTSequence`s are tied to `AST`s. Simply use lists to store sequences of `AST`s.

https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes
