### ISSUE TITLE
Update homebrew package

### ISSUE THREAD

**Issue by domoritz** [potassco/clingo#48]
It would be awesome if gringo/clingo was available via homebrew. There is already a gringo formula: https://github.com/Homebrew/homebrew-core/blob/c24a2bbdf6d7fdf5820b6a44ad8926933ee53f21/Formula/gringo.rb.

**Comment by rkaminsk** [comment]
There is a gringo homebrew package also including clingo. Unfortunately, it is for gringo/clingo version 4. Also, I am not maintaing the homebrew packages. You could contact the maintainer of the package (or if you want something to happen soon provide a formula to build clingo 5 yourself).

I am not going to maintain MacOS packages because I do not use the operating system. If you have specific questions on how to build clingo on MacOS, you can ask here of course or use our mailing list.

**Comment by domoritz** [comment]
Clingo is now available on homebrew: http://www.brewformulas.org/Clingo.
