### ISSUE TITLE
The 'clingo' command conflcts with the same command from the 'gringo' package

### ISSUE THREAD

**Issue by yurivict** [potassco/clingo#80]
http://potassco.sourceforge.net

Is ```gringo``` obsolete?

**Comment by rkaminsk** [comment]
For most users `clingo` is more convenient, because there is no need for a separate `solver` and `gringo` functionality is also offered by calling `clingo --mode=gringo`. Also the combination of `gringo` and `clasp` offers much more functionality than using both systems in a pipe. Still `gringo` is part of `clingo` and build from the same source. For other people developing their own solvers `gringo` might be interesting if they don't need our solver.
